name: Auto Tweet Bot

on:
  schedule:
    # Posts every hour
    - cron: "* */4 * * *"
    # Change to your preferred schedule:
    # '0 */2 * * *' = every 2 hours
    # '0 */6 * * *' = every 6 hours (4x per day)
    # '0 9,15,21 * * *' = 9am, 3pm, 9pm

  workflow_dispatch: # Allows manual trigger

jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Post tweet
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          CONTENT_TYPE: ${{ secrets.CONTENT_TYPE }}
          RUN_ONCE: "true"
        run: bun run src/functions/bot.ts
